# type: ignore
"""history

Revision ID: 37466358a445
Revises: 9886c8fd2b18
Create Date: 2020-02-24 22:28:55.993309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37466358a445"
down_revision = "9886c8fd2b18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history", sa.Column("device_id", sa.String(length=255), nullable=False)
    )
    op.drop_column("history", "user_role")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history",
        sa.Column("user_role", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("history", "device_id")
    # ### end Alembic commands ###
