# type: ignore
"""unique history

Revision ID: 6a4b7c336e0e
Revises: d8e9859f3cbc
Create Date: 2020-03-11 21:25:12.173699

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "6a4b7c336e0e"
down_revision = "d8e9859f3cbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_history_point", "history", ["device_id", "ts"], unique=False)
    op.create_index(op.f("ix_history_ts"), "history", ["ts"], unique=False)
    op.create_unique_constraint(
        op.f("uq_history_device_id"), "history", ["device_id", "ts"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_history_device_id"), "history", type_="unique")
    op.drop_index(op.f("ix_history_ts"), table_name="history")
    op.drop_index("idx_history_point", table_name="history")
    # ### end Alembic commands ###
