"""Create Users Table 

Revision ID: 6e7ea92b3444
Revises: 
Create Date: 2019-12-01 12:24:33.146412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e7ea92b3444"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_role", sa.Integer(), nullable=False),
        sa.Column("password", sa.String(length=255), server_default="", nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "first_name", sa.String(length=255), server_default="", nullable=False
        ),
        sa.Column(
            "last_name", sa.String(length=255), server_default="", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
