# type: ignore
"""more history

Revision ID: 9886c8fd2b18
Revises: 6e7ea92b3444
Create Date: 2020-02-24 21:30:36.404314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9886c8fd2b18"
down_revision = "6e7ea92b3444"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_role", sa.Integer(), nullable=False),
        sa.Column("td", sa.DateTime(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_history")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("history")
    # ### end Alembic commands ###
