# type: ignore
"""history - device id 

Revision ID: b6cf0738c323
Revises: 37466358a445
Create Date: 2020-02-25 17:54:33.132512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6cf0738c323"
down_revision = "37466358a445"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("history", sa.Column("ts", sa.DateTime(), nullable=False))
    op.create_index(
        op.f("ix_history_device_id"), "history", ["device_id"], unique=False
    )
    op.drop_column("history", "td")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history",
        sa.Column("td", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_history_device_id"), table_name="history")
    op.drop_column("history", "ts")
    # ### end Alembic commands ###
